### ISSUE TITLE
Params that initiates with same chars can confuse PhpDocReader

### ISSUE THREAD

**Issue by jaacoder** [PHP-DI/PhpDocReader#11]
If the method contains params with same initials, ex.: ```$ci``` and ```$city``` can sometimes confuse PhpDocReader and it thinks both are the same time while being acctually different.

**Comment by mnapoli** [comment]
Hi @jaacoder, thanks for the report. After a quick look it might be because of these regular expressions:

- https://github.com/PHP-DI/PhpDocReader/blob/master/src/PhpDocReader/PhpDocReader.php#L166
- https://github.com/PHP-DI/PhpDocReader/blob/master/src/PhpDocReader/PhpDocReader.php#L81

If you have time to write a test and a fix feel free to send a pull request.
